POST http://127.0.0.1:8000/root/currency/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYyNDk2MTA0LCJpYXQiOjE2NjI0OTI1MDQsImp0aSI6Ijk2MzE2MmIzMmE3ZjRjYTViYjA2MGM5NzJiNGFmM2U0IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290QHVuaS5jbG91ZCIsImZpcnN0X25hbWUiOiJSb290IiwibGFzdF9uYW1lIjoiVXNlciBVbmkuQ2xvdWQiLCJpc19zdXBlcnVzZXIiOnRydWUsImlzX3N0YWZmIjp0cnVlLCJlbWFpbCI6InJvb3RAdW5pLmNsb3VkIn0.oYLVKucKDnN26tiQDe3bHjzPG6l3czTalUc7tI4xhDQ

{
    "currency": "usd",
    "unicloud_dollar": 5.50,
    "safety_margin": 15
}

###

GET http://127.0.0.1:8000/root/currency/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYyNDk2MTA0LCJpYXQiOjE2NjI0OTI1MDQsImp0aSI6Ijk2MzE2MmIzMmE3ZjRjYTViYjA2MGM5NzJiNGFmM2U0IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290QHVuaS5jbG91ZCIsImZpcnN0X25hbWUiOiJSb290IiwibGFzdF9uYW1lIjoiVXNlciBVbmkuQ2xvdWQiLCJpc19zdXBlcnVzZXIiOnRydWUsImlzX3N0YWZmIjp0cnVlLCJlbWFpbCI6InJvb3RAdW5pLmNsb3VkIn0.oYLVKucKDnN26tiQDe3bHjzPG6l3czTalUc7tI4xhDQ

{
}
###

DELETE http://127.0.0.1:8000/root/currency/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYyNDk2MTA0LCJpYXQiOjE2NjI0OTI1MDQsImp0aSI6Ijk2MzE2MmIzMmE3ZjRjYTViYjA2MGM5NzJiNGFmM2U0IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290QHVuaS5jbG91ZCIsImZpcnN0X25hbWUiOiJSb290IiwibGFzdF9uYW1lIjoiVXNlciBVbmkuQ2xvdWQiLCJpc19zdXBlcnVzZXIiOnRydWUsImlzX3N0YWZmIjp0cnVlLCJlbWFpbCI6InJvb3RAdW5pLmNsb3VkIn0.oYLVKucKDnN26tiQDe3bHjzPG6l3czTalUc7tI4xhDQ

{
    "currency_id": 3
}