POST http://127.0.0.1:8000/root/partner/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYxOTgzMjc4LCJpYXQiOjE2NjE5Nzk2NzgsImp0aSI6IjlmODkzNGM1MDc3MzRhMTJiYjc3ZjU1OTkxNmRkNjBlIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290QHVuaS5jbG91ZCIsImZpcnN0X25hbWUiOiJSb290IiwibGFzdF9uYW1lIjoiVXNlciBVbmkuQ2xvdWQiLCJpc19zdXBlcnVzZXIiOnRydWUsImlzX3N0YWZmIjp0cnVlLCJlbWFpbCI6InJvb3RAdW5pLmNsb3VkIn0.h5OxMAzIraL8nQyy-3PC6L85HFILAl8TOJR12Fay2r0

{
    "cnpj": "99999999999999",
    "email": "felipegatefy+10@gmail.com",
}
###
