GET http://127.0.0.1:8000/menu/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYyMTUzNzkyLCJpYXQiOjE2NjIxNTAxOTIsImp0aSI6IjJiZGEwNWJmZTU3ZTRhNjBhODFlY2RhOTllYmRkM2YxIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290QHVuaS5jbG91ZCIsImZpcnN0X25hbWUiOiJSb290IiwibGFzdF9uYW1lIjoiVXNlciBVbmkuQ2xvdWQiLCJpc19zdXBlcnVzZXIiOnRydWUsImlzX3N0YWZmIjp0cnVlLCJlbWFpbCI6InJvb3RAdW5pLmNsb3VkIn0.hWbloeCp6n4GlD7sZYRaBLSUCFZBeF-LG-LVlCcVf-s

{
}