# Generated by Django 4.0.2 on 2022-04-06 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(auto_created=True, default=True, null=True)),
                ('razao_social', models.CharField(max_length=250)),
                ('telefone', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bairro', models.CharField(blank=True, max_length=250, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=250, null=True)),
                ('numero', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_fantasia', models.CharField(max_length=250, null=True)),
                ('natureza_juridica', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(blank=True, max_length=250, null=True)),
                ('cnpj', models.CharField(max_length=25)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unicloud_customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicloud_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='unicloud_customers.customer')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner', to='unicloud_customers.customer')),
            ],
        ),
    ]
