# Generated by Django 4.0.2 on 2022-04-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteduser',
            name='token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
