# Generated by Django 4.0.2 on 2022-05-19 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unicloud_server.custom_azure


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicloud_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizationLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(storage=unicloud_server.custom_azure.AzureMediaStorage, upload_to='logo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicloud_customers.customer')),
            ],
        ),
    ]
