# Generated by Django 4.0.2 on 2022-05-23 15:23

from django.db import migrations, models
import unicloud_customers.models
import unicloud_server.custom_azure


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_customers', '0002_alter_usercustomer_user_organizationlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlogo',
            name='logo',
            field=models.ImageField(storage=unicloud_server.custom_azure.AzureMediaStorage, upload_to=unicloud_customers.models.customer_directory_path),
        ),
    ]
