# Generated by Django 4.0.2 on 2022-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_customers', '0003_alter_organizationlogo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteduser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
