# Generated by Django 4.0.6 on 2022-07-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_customers', '0005_customerrequest_customerhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerrequest',
            name='partner',
        ),
        migrations.DeleteModel(
            name='CustomerHistory',
        ),
        migrations.DeleteModel(
            name='CustomerRequest',
        ),
    ]
