# Generated by Django 4.0.6 on 2022-07-20 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unicloud_resources', '0002_assets_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicloud_customers', '0006_remove_customerrequest_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_description', models.TextField()),
                ('status', models.CharField(default='opportunity_pending', max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_customer_opportunity', to='unicloud_customers.customer')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_partner_opportunity_requester', to='unicloud_customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_user_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRelatioshipFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_author', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_to_sale', to='unicloud_customers.customer')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_sales', to='unicloud_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceOfOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='the_sales_opportunity', to='unicloud_sales.opportunity')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_of_sales_opportunity', to='unicloud_resources.resource')),
            ],
        ),
    ]
