# Generated by Django 4.0.6 on 2022-07-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_sales', '0002_opportunity_opportunity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrelatioshipflow',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_of_activity', to='unicloud_sales.opportunity'),
        ),
    ]
