# Generated by Django 4.0.7 on 2022-09-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_sales', '0005_delete_calculator_delete_measureunit_delete_ratios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('months', models.IntegerField()),
                ('discount', models.FloatField()),
            ],
        ),
    ]
