# Generated by Django 4.0.7 on 2022-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_sales', '0006_subscriptionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
