# Generated by Django 4.0.7 on 2022-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_sales', '0007_measuremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicloud_dollar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('safety_margin', models.FloatField()),
            ],
        ),
    ]
