# Generated by Django 4.0.7 on 2022-09-06 19:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_sales', '0008_currencymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='safety_margin',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='unicloud_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
