# Generated by Django 4.0.7 on 2022-09-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_sales', '0010_currencymodel_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencymodel',
            old_name='unicloud_dollar',
            new_name='unicloud_currency',
        ),
    ]
