# Generated by Django 4.0.6 on 2022-07-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unicloud_contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=150)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicloud_resources.resourcestype')),
            ],
        ),
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicloud_contracts.contracts')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unicloud_resources.resource')),
            ],
        ),
    ]
