# Generated by Django 4.0.6 on 2022-07-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='qty',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
