# Generated by Django 4.0.6 on 2022-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_resources', '0002_assets_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='monthly_houer',
            field=models.IntegerField(auto_created=True, default=730),
        ),
        migrations.AddField(
            model_name='resource',
            name='unit_type',
            field=models.CharField(default='GB', max_length=150),
        ),
        migrations.AddField(
            model_name='resource',
            name='value_unit',
            field=models.IntegerField(default=0.1),
        ),
    ]
