# Generated by Django 4.0.6 on 2022-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_resources', '0003_resource_monthly_houer_resource_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='value_unit',
            field=models.FloatField(default=0.1),
        ),
    ]
