# Generated by Django 4.0.6 on 2022-08-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_resources', '0004_alter_resource_value_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='value_unit',
        ),
    ]
