# Generated by Django 4.0.6 on 2022-07-15 18:33

from django.db import migrations, models
import django.db.models.deletion
import unicloud_contracts.models
import unicloud_server.custom_azure


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unicloud_customers', '0004_alter_inviteduser_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term', models.IntegerField()),
                ('readjust_cycle', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('note', models.TextField()),
                ('contract', models.FileField(storage=unicloud_server.custom_azure.AzureContractsStorage, upload_to=unicloud_contracts.models.customer_directory_path)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicloud_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicloud_contracts.contracts')),
                ('intermediary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicloud_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unicloud_contracts.contracts')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unicloud_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unicloud_contracts.contracts')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unicloud_customers.customer')),
            ],
        ),
    ]
