# Generated by Django 4.0.6 on 2022-07-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_contracts', '0004_alter_contracts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
