# Generated by Django 4.0.6 on 2022-08-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_users', '0006_rename_userpreferences_userpreferencesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferencesmodel',
            old_name='langague',
            new_name='language',
        ),
    ]
