# Generated by Django 4.0.6 on 2022-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_users', '0007_rename_langague_userpreferencesmodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferencesmodel',
            name='language',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferencesmodel',
            name='theme',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
