# Generated by Django 4.0.2 on 2022-06-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_pods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadarapods',
            name='domain_tenant',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
