# Generated by Django 4.0.2 on 2022-06-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_pods', '0002_zadarapods_domain_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadarapods',
            name='access_token',
            field=models.CharField(default=None, max_length=100000, null=True),
        ),
    ]
