# Generated by Django 4.0.2 on 2022-06-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_pods', '0003_zadarapods_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zadarapods',
            name='domain_tenant',
        ),
        migrations.RemoveField(
            model_name='zadarapods',
            name='pod_password',
        ),
        migrations.RemoveField(
            model_name='zadarapods',
            name='pod_user',
        ),
    ]
