# Generated by Django 4.0.2 on 2022-06-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_pods', '0004_remove_zadarapods_domain_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadarapods',
            name='spare_nodes',
            field=models.IntegerField(default=0),
        ),
    ]
