# Generated by Django 4.0.2 on 2022-06-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_pods', '0006_remove_zadarapods_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadarapods',
            name='projetct_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
