# Generated by Django 4.0.2 on 2022-06-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicloud_pods', '0007_zadarapods_projetct_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zadarapods',
            old_name='projetct_id',
            new_name='project_id',
        ),
    ]
